"""removed proxy

Revision ID: 715d3c984272
Revises: 7d95c4407c4b
Create Date: 2024-04-11 00:11:47.471517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715d3c984272'
down_revision = '7d95c4407c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('registration_date', sa.DateTime(), nullable=True))
    op.drop_column('registrations', 'end_date')
    op.drop_column('registrations', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('start_date', sa.DATETIME(), nullable=True))
    op.add_column('registrations', sa.Column('end_date', sa.DATETIME(), nullable=True))
    op.drop_column('registrations', 'registration_date')
    # ### end Alembic commands ###
